# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "catppuccin_latte", "catppuccin_mocha"

# Site Settings
locale                   : "zh-CN"
rtl                      :
title                    : "慧珍的小窝"
title_separator          : "-"
subtitle                 : "充满好奇 | 记录生活"
name                     : "姜慧珍"
description              : "看看你都在做什么"
url                      :
baseurl                  :
repository               :
teaser                   :
logo                     :
masthead_title           :
breadcrumbs              : true
words_per_minute         : 200
enable_copy_code_button  : true
copyright                : "姜慧珍"
copyright_url            :
comments:
  provider               : false
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
  utterances:
    theme                :
  giscus:
    theme                :
  staticman:
    branch               :
reCaptcha:
  siteKey                :
atom_feed:
  hide                   : true
search                   : true
search_full_content      : true
search_provider          : lunr

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
social:
  type                   : Person
  name                   : "姜慧珍"

# Analytics
analytics:
  provider               : false

# Site Author
author:
  name             : "姜慧珍"
  avatar           : "https://avatars.githubusercontent.com/jiang97h"
  bio              : "充满好奇"
  location         : "天上"
  email            : 1846301202@qq.com
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jiang97h"

# Site Navigation（汉化导航栏）
nav:
  - title: "文章"
    url: /posts/
  - title: "分类"
    url: /categories/
  - title: "标签"
    url: /tags/
  - title: "关于"
    url: /about/

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jiang97h"
  since: "2026"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai

# Pagination
paginate: 5
paginate_path: /page:num/

pagination:
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail:
    before: 2
    after: 2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
